export const CRASH_ABI = [
  { name: "openRound",          type: "function", inputs: [{ name: "commitment", type: "bytes32" }], outputs: [], stateMutability: "nonpayable" },
  { name: "startRound",         type: "function", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { name: "placeBet",           type: "function", inputs: [{ name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { name: "cashOut",            type: "function", inputs: [{ name: "multiplier", type: "uint32" }], outputs: [], stateMutability: "nonpayable" },
  { name: "revealCrash",        type: "function", inputs: [{ name: "crashPoint", type: "uint32" }, { name: "salt", type: "bytes32" }], outputs: [], stateMutability: "nonpayable" },
  { name: "getCurrentRound",    type: "function", inputs: [], outputs: [{ name: "", type: "tuple", components: [
    { name: "roundId",    type: "uint256" },
    { name: "commitment", type: "bytes32" },
    { name: "crashPoint", type: "uint32" },
    { name: "phase",      type: "uint8" },
    { name: "totalBets",  type: "uint256" },
    { name: "startTime",  type: "uint256" },
  ]}], stateMutability: "view" },
  { name: "getMyBet",           type: "function", inputs: [{ name: "roundId", type: "uint256" }], outputs: [{ name: "", type: "tuple", components: [
    { name: "amount",      type: "uint256" },
    { name: "cashedOutAt", type: "uint32" },
    { name: "claimed",     type: "bool" },
  ]}], stateMutability: "view" },
  { name: "currentRoundId",     type: "function", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { name: "BetPlaced",          type: "event",    inputs: [{ name: "roundId", type: "uint256", indexed: true }, { name: "player", type: "address", indexed: true }, { name: "amount", type: "uint256" }] },
  { name: "CashedOut",          type: "event",    inputs: [{ name: "roundId", type: "uint256", indexed: true }, { name: "player", type: "address", indexed: true }, { name: "multiplier", type: "uint32" }, { name: "payout", type: "uint256" }] },
  { name: "RoundLive",          type: "event",    inputs: [{ name: "roundId", type: "uint256", indexed: true }, { name: "startTime", type: "uint256" }] },
  { name: "RoundRevealed",      type: "event",    inputs: [{ name: "roundId", type: "uint256", indexed: true }, { name: "crashPoint", type: "uint32" }] },
] as const;

export const PREDICTION_ABI = [
  { name: "placeBet",    type: "function", inputs: [{ name: "marketId", type: "uint256" }, { name: "outcome", type: "uint8" }, { name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { name: "claim",       type: "function", inputs: [{ name: "marketId", type: "uint256" }, { name: "positionIndex", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { name: "getMarket",   type: "function", inputs: [{ name: "marketId", type: "uint256" }], outputs: [
    { name: "id",             type: "uint256" },
    { name: "question",       type: "string" },
    { name: "outcomes",       type: "string[]" },
    { name: "deadline",       type: "uint256" },
    { name: "status",         type: "uint8" },
    { name: "winningOutcome", type: "uint8" },
    { name: "totalPool",      type: "uint256" },
    { name: "outcomePools",   type: "uint256[]" },
    { name: "category",       type: "string" },
  ], stateMutability: "view" },
  { name: "getPositions",   type: "function", inputs: [{ name: "marketId", type: "uint256" }, { name: "player", type: "address" }], outputs: [{ name: "", type: "tuple[]", components: [{ name: "amount", type: "uint256" }, { name: "outcome", type: "uint8" }, { name: "claimed", type: "bool" }] }], stateMutability: "view" },
  { name: "getMarketOdds",  type: "function", inputs: [{ name: "marketId", type: "uint256" }], outputs: [{ name: "odds", type: "uint256[]" }], stateMutability: "view" },
  { name: "marketCount",    type: "function", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { name: "BetPlaced",      type: "event", inputs: [{ name: "marketId", type: "uint256", indexed: true }, { name: "player", type: "address", indexed: true }, { name: "outcome", type: "uint8" }, { name: "amount", type: "uint256" }] },
  { name: "MarketResolved", type: "event", inputs: [{ name: "marketId", type: "uint256", indexed: true }, { name: "winningOutcome", type: "uint8" }] },
] as const;

export const CHESS_ABI = [
  { name: "createChallenge",  type: "function", inputs: [{ name: "stake", type: "uint256" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "nonpayable" },
  { name: "acceptChallenge",  type: "function", inputs: [{ name: "gameId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { name: "attestResult",     type: "function", inputs: [{ name: "gameId", type: "uint256" }, { name: "result", type: "uint8" }], outputs: [], stateMutability: "nonpayable" },
  { name: "cancelChallenge",  type: "function", inputs: [{ name: "gameId", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { name: "getGame",          type: "function", inputs: [{ name: "gameId", type: "uint256" }], outputs: [{ name: "", type: "tuple", components: [
    { name: "id",                type: "uint256" },
    { name: "white",             type: "address" },
    { name: "black",             type: "address" },
    { name: "stake",             type: "uint256" },
    { name: "status",            type: "uint8" },
    { name: "result",            type: "uint8" },
    { name: "createdAt",         type: "uint256" },
    { name: "startedAt",         type: "uint256" },
    { name: "whiteAttestation",  type: "uint8" },
    { name: "blackAttestation",  type: "uint8" },
    { name: "pgn",               type: "string" },
  ]}], stateMutability: "view" },
  { name: "getOpenChallenges", type: "function", inputs: [{ name: "fromId", type: "uint256" }, { name: "limit", type: "uint256" }], outputs: [{ name: "ids", type: "uint256[]" }], stateMutability: "view" },
  { name: "activeGame",        type: "function", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { name: "gameCount",         type: "function", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { name: "GameCreated",       type: "event", inputs: [{ name: "id", type: "uint256", indexed: true }, { name: "white", type: "address", indexed: true }, { name: "stake", type: "uint256" }] },
  { name: "GameAccepted",      type: "event", inputs: [{ name: "id", type: "uint256", indexed: true }, { name: "black", type: "address", indexed: true }] },
  { name: "GameResolved",      type: "event", inputs: [{ name: "id", type: "uint256", indexed: true }, { name: "result", type: "uint8" }, { name: "winner", type: "address" }] },
] as const;

export const BLACKJACK_ABI = [
  { name: "startGame",      type: "function", inputs: [{ name: "bet", type: "uint256" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "nonpayable" },
  { name: "hit",            type: "function", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { name: "stand",          type: "function", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { name: "getSession",     type: "function", inputs: [{ name: "sessionId", type: "uint256" }], outputs: [{ name: "", type: "tuple", components: [
    { name: "player",      type: "address" },
    { name: "bet",         type: "uint256" },
    { name: "commitment",  type: "bytes32" },
    { name: "clientSeed",  type: "bytes32" },
    { name: "state",       type: "uint8" },
    { name: "playerCards", type: "uint8[]" },
    { name: "dealerCards", type: "uint8[]" },
    { name: "playerTotal", type: "uint8" },
    { name: "dealerTotal", type: "uint8" },
    { name: "isBlackjack", type: "bool" },
    { name: "playerBust",  type: "bool" },
    { name: "createdAt",   type: "uint256" },
  ]}], stateMutability: "view" },
  { name: "activeSession",  type: "function", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { name: "houseBalance",   type: "function", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { name: "cardToString",   type: "function", inputs: [{ name: "card", type: "uint8" }], outputs: [{ name: "rank", type: "string" }, { name: "suit", type: "string" }], stateMutability: "pure" },
  { name: "GameStarted",    type: "event", inputs: [{ name: "sessionId", type: "uint256", indexed: true }, { name: "player", type: "address", indexed: true }, { name: "bet", type: "uint256" }] },
  { name: "GameSettled",    type: "event", inputs: [{ name: "sessionId", type: "uint256", indexed: true }, { name: "result", type: "uint8" }, { name: "payout", type: "uint256" }] },
] as const;

export const ERC20_ABI = [
  { name: "approve",      type: "function", inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable" },
  { name: "allowance",    type: "function", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { name: "balanceOf",    type: "function", inputs: [{ name: "account", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { name: "decimals",     type: "function", inputs: [], outputs: [{ name: "", type: "uint8" }], stateMutability: "view" },
  { name: "Approval",     type: "event",    inputs: [{ name: "owner", type: "address", indexed: true }, { name: "spender", type: "address", indexed: true }, { name: "value", type: "uint256" }] },
] as const;
